---
- name: Calculating Ansible version
  set_fact:
    ansible_version: "{{ ansible.version | calculate( ansible.latest ) }}"

- name: Installing Python packages
  apt:  name={{item}} state=latest force=yes
  with_items:
    - python-pip
    - python-dev

- name: Installing base pip packages
  pip:  name={{ item }} state=latest
  with_items:
    - httplib2 # Missing on AWS Ubuntu AMI

- name: Installing Ansible
  pip:  name=ansible version={{ ansible_version }} extra_args="--upgrade"

- name: Creating Ansible inventory file
  file:
    path:  "{{ ansible.inventory_file|dirname }}"
    state: directory
- file:
    path:  "{{ ansible.inventory_file }}"
    state: touch
- lineinfile:
    dest:  "{{ ansible.inventory_file }}"
    line:  localhost

- name:     Running Ansible version
  command:  ansible --version
  register: ansible_version_out

- name:     Running Ansible Playbook version
  command:  ansible-playbook --version
  register: ansible_playbook_version_out

- name:     Running Ansible setup module
  command:  ansible localhost -c local -m setup
  register: inventory_out

- name: Verifying Ansible version
  assert:
    that:
      - ansible_version     in ansible_version_out.stdout
      - ansible_version     in ansible_playbook_version_out.stdout
      - "'ansible'          in ansible_version_out.stdout"
      - "'ansible-playbook' in ansible_playbook_version_out.stdout"
      - "'ansible_facts'    in inventory_out.stdout"
      - "'Ubuntu'           in inventory_out.stdout"
