---
- include: verify-master.yml master={{ helios_master }}

- set_fact:
    registrar_plugin: "{{ helios.agent.registrar_plugin.jar | tokens( helios.agent.registrar_plugin ) }}"

- name: Stopping Helios agent service
  service: name=helios-agent state=stopped
  ignore_errors: yes

- name: Downloading registrar plugin
  get_url:
    url:  "{{ helios.agent.registrar_plugin.url | tokens( helios.agent.registrar_plugin ) }}"
    dest: "{{ registrar_plugin }}"

- include: "{{ common.utils.mkdir }}"
  vars:
    file:  "{{ helios.agent.config_endpoints }}"

- name: Copying Helios agent configs
  template:
    src:  "{{ item.from }}"
    dest: "{{ item.to   }}"
  with_items:
    - { from: 'agent-config',           to: "{{ helios.agent.config }}" }
    - { from: 'agent-config-endpoints', to: "{{ helios.agent.config_endpoints }}" }

- name: Installing Helios agent
  apt:  deb="{{ helios.home }}/helios-agent_{{ helios_version }}_all.deb"

- name: Starting Helios agent service
  service: name=helios-agent state=started enabled=yes
