---
- name: Calculating Groovy version
  set_fact:
    groovy_version: "{{ groovy.version | calculate( groovy.latest ) }}"

- include: "{{ common.utils.download }}"
  vars:
    title:   Groovy
    url:     "{{ groovy.url     | tokens({ 'version': groovy_version }) }}"
    archive: "{{ groovy.archive | tokens({ 'version': groovy_version }) }}"
    home:    "{{ groovy.home }}"
    env:     "{{ groovy_env }}"
    tests:
      - { run: "groovy   --version", expect: "Groovy Version: {{ groovy_version }}" }
      - { run: "grape    --version", expect: "Groovy Version: {{ groovy_version }}" }
      - { run: "groovysh --version", expect: "Groovy Shell {{ groovy_version }}" }
      - { run: "groovyc  --version", expect: "Groovy compiler version {{ groovy_version }}" }
