---
- name: Updating Ubuntu repo
  replace:
    dest:    "{{ ubuntu.sources_list }}"
    regexp:  'http:\/\/archive\.ubuntu\.com\/ubuntu'
    replace: "{{ ubuntu.apt_repo }}"
    backup:  yes

- name:     Listing Ubuntu repos
  shell:    grep 'http://' '{{ ubuntu.sources_list }}' | grep -v '#' | awk '{print $2}' | uniq | sort
  register: ubuntu_repos

- debug: var=ubuntu_repos.stdout_lines

- name: Updating 'apt' cache
  apt:  update_cache=yes

- name: Upgrading installed packages
  apt:  upgrade=dist
  when: ( not is_docker|bool )

- name: Installing base packages
  apt:  name={{ item }} state=latest force=yes
  with_items:
    - vim
    - htop
    - wget
    - curl
    - git
    - zip
    - unzip
    - upstart
    - man
    - build-essential
    - psmisc # Needed for 'killall'

- name:    Stopping and disabling Chef service, if found
  service: name=chef-client state=stopped enabled=no
  ignore_errors: yes

- name:    Stopping and disabling Puppet service, if found
  service: name=puppet state=stopped enabled=no
  ignore_errors: yes
