---
- set_fact:
    nexus_port: "{{ nexus_port | default( nexus.port ) }}"

  # -----------------------
  # Standalone
  # -----------------------

- set_fact:
    nexus_home: "{{ nexus.standalone.home }}/nexus-{{ nexus.version }}"
  when: nexus.run == 'standalone'

- include: "{{ common.utils.service }}"
  vars:
    service: nexus
    title:   Nexus
    url:     "{{ nexus.standalone.url     | tokens( nexus ) }}"
    archive: "{{ nexus.standalone.archive | tokens( nexus ) }}"
    home:    "{{ nexus.standalone.home }}"
    env:
      RUN_AS_USER: root
    configs:
      - { from: nexus.properties, to: "{{ nexus_home }}/conf/nexus.properties" }
    command: "{{ nexus_home }}/bin/nexus console"
    port:    "{{ nexus_port }}"
    timeout: "{{ nexus.timeout }}"
    wait:    "{{ nexus.wait }}"
    verify:  "{{ nexus.verify }}"
  when: nexus.run == 'standalone'

  # -----------------------
  # War
  # -----------------------

- include: "{{ common.roles.tomcat }}"
  vars:
    tomcat_port: "{{ nexus_port }}"
  when: nexus.run == 'war'

- include: "{{ common.utils.service }}"
  vars:
    service: nexus
    title:   Nexus
    url:     "{{ nexus.war.url     | tokens( nexus ) }}"
    archive: "{{ nexus.war.archive | tokens( nexus ) }}"
    home:    "{{ tomcat_webapps }}/{{ nexus.war.home }}"
    command: "{{ tomcat_run  }}"
    port:    "{{ nexus_port }}"
    timeout: "{{ nexus.timeout }}"
    wait:    "{{ nexus.wait }}"
    verify:  "{{ nexus.verify }}"
  when: nexus.run == 'war'
