---
# Asgard playbook for Ubuntu
# https://github.com/Netflix/asgard

- name:  Asgard
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml
    - [ roles/asgard/vars/aws.yml, vars/common.yml ]

  roles:
    - { role: run-before, period: daily }
    - asgard
    - run-after
