---
# Jenkins playbook for Ubuntu
# http://jenkins-ci.org/

- name:  Jenkins
  hosts: all
  sudo:  yes

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution }}.yml

  roles:
    - { role: run-before, period: daily }
    - jenkins
    - run-after
