---
- set_fact:
    zookeeper_home: "{{ zookeeper.home }}/zookeeper-{{ zookeeper.version }}"
    zookeeper_port: "{{ zookeeper_port | default( zookeeper.port ) }}"

- include: "{{ common.utils.service }}"
  vars:
    title:    ZooKeeper
    service:  zookeeper
    url:     "{{ zookeeper.url     | tokens( zookeeper ) }}"
    archive: "{{ zookeeper.archive | tokens( zookeeper ) }}"
    home:    "{{ zookeeper.home }}"
    configs:
      - { from: zoo.cfg, to: "{{ zookeeper_home }}/conf/zoo.cfg" }
    command: "{{ zookeeper_home }}/bin/zkServer.sh start-foreground"
    port:    "{{ zookeeper_port }}"

- name: Running zkCli
  shell:    "echo 'ls /' | {{ zookeeper_home }}/bin/zkCli.sh -server {{ common.net.localhost }}:{{ zookeeper_port }}"
  register: zk_out

- name: Verifying zkCli
  fail: msg="Failed to execute zkCli - {{ zk_out }}"
  when: "'{{ common.net.localhost }}:{{ zookeeper_port }}(CONNECTED)' not in zk_out.stdout"
