---
- set_fact:
    etcd_dir:  "{{ etcd.dir_name | tokens( etcd ) }}"
- set_fact:
    etcd_bin:  "{{ etcd.home }}/{{ etcd_dir }}/etcd"
    etcd_port: "{{ etcd_port | default( etcd.port ) }}"

- include: "{{ common.utils.service }}"
  vars:
    service: etcd
    title:   etcd
    url:     "{{ etcd.url     | tokens({ 'dir_name': etcd_dir, 'version': etcd.version }) }}"
    archive: "{{ etcd.archive | tokens( etcd ) }}"
    home:    "{{ etcd.home }}"
    env:
      # https://github.com/coreos/etcd/blob/master/Documentation/configuration.md
      ETCD_ADDR:      "{{ common.net.localhost }}:{{ etcd_port }}"
      ETCD_BIND_ADDR: "{{ common.net.any_ip }}:{{ etcd_port }}"
    tests:
      - { run: "{{ etcd_bin }} --version", expect: "{{ etcd.version }}" }
    command: "{{ etcd_bin }} $ETCD_OPTS"
    port:    "{{ etcd_port }}"
    verify:
      - { path: /version, content: "{{ etcd.version }}" }
